---
title: "Titulo del taller"
author: "Autor del Taller"
date: "AAAA-MM-DD (Fecha de elaboración)"
output:
  html_document:
    include:
      before_body: header.html
      after_body: footer.html
    css: style.css
  pdf_document: default
image: null
editor_options:
  markdown:
    wrap: 72
licenses: "CC-BY"
---

## Introducción (Sección 1)

Aquí se espera que usted comparta información sobre un problema de salud pública. La metodología es de resolución de casos.

###Ejemplo de la introducción:

Hay un brote por un patógeno nuevo en su ciudad. 


Las características de la enfermedad son:

- Según información de otros países, se sabe que la transmisión ocurre de persona a persona. (por via respiratoria/sexual)?
- Se conoce que existe una proporción de casos asintomáticos
- Los síntomas incluyen cefalea, fiebre, escalofríos, inflamación de los ganglios linfáticos, agotamiento, dolores musculares y de espalda, y síntomas respiratorios.
- Se han reportado casos de personas con un sarpullido en la zona de las manos, los pies, el pecho, el rostro, la boca, o cerca de la zona genital.
- Algunos casos requieren hospitalización debido a daño sistémico.
- Se desconoce el riesgo de muerte
- No existe vacuna ni tratamiento específico para esta enfermedad.


Si bien estos síntomas son similares a los de algunas patologías conocidas, existen desafíos adicionales. Debido al temor que causa la estigmatización, las personas prefieren no compartir información sobre sus contactos o su enfermedad. Esto lleva a que exista dificultad para determinar ciertos parámetros, como la fecha exacta de contagio y la identificación del individuo fuente. Además, hay preocupaciones acerca de la difusión de información porque es una enfermedad que puede manifestarse en la zona genital, lo que puede incrementar el estigma social asociado. 

Usted, como epidemiólogo, debe hacer recomendaciones sobre cómo controlar el brote. El sistema de vigilancia epidemiológica le proporciona unas bases de datos e información relevante. Su tarea es diseñar el mejor programa para controlar este brote.


#### Las bases de datos que usted recibe contienen

##### Base 1. Base casos

- Fecha de inicio de síntomas
- Fecha de salpullido
- Fecha de exposición al contacto
- Sexo
- Edad
- Contacto

##### Base 2. Base contactos

- Edad
- Sexo
- Fecha de exposición al caso

Con esta información en conjunto con el resto de información le debe permitir diseñar el programa de control. Recuerde que el respeto por la privacidad,  dignidad de las personas y comunicación del riesgo son clave en el diseño de cualquier programa de control.

(También es posible pedir a los participantes que describan la base de datos)

## Objetivos (Sección 2)

Aquí se espera que usted incluya los objetivos del taller. ¿Qué es lo que usted espera que los estudiantes aprendan del taller? ¿Qué se espera que los estudiantes puedan hacer al terminar el taller? Los objetivos deben empezar con un verbo en infinitivo.

###Ejemplo de los objetivos:

- Identificar los parámetros necesarios en casos de  transmisión de enfermedades infecciosas de persona a persona. 
- Entender la importancia de estimar correctamente los parámetros en brotes de enfermedades transmitidas de persona a persona.
- Estimar el periodo de incubación y el intervalo serial. 
- Identificar la probable vía de contagio.
- Describir la estructura de los contactos.
- Analizar las dificultades que se presentan al determinar la fecha de contagio y la fuente de infección.
- Reconocer las limitaciones en la difusión de datos debido a factores socioculturales.
- Diseñar estrategias para rastrear y gestionar contactos, reconociendo desafíos en el proceso.
- Utilizar herramientas, como el paquete epicontacts, para analizar y visualizar la cadena de transmisión.

## Conceptos básicos a desarrollar (Sección 3)

En esta práctica se desarrollarán los siguientes conceptos:

Aquí se espera que usted mencione los conceptos más importantes del taller (deben ser conceptos técnicos que se puedan encontrar en la literatura)

###Ejemplo de los conceptos

- Transmisión de enfermedades infecciosas de persona a persona
- Mecanismos de transmisión
- Fecha de contagio
- Fuente de contagio
- Cadena de transmisión


### Contenido del taller (Sección 4)

Aquí debe agregar el contenido del taller. Sea claro. Pruebe los códigos. Recuerde que si bien estará usted para dirigir el taller, el taller debe ser claro para poder ser ejecutado.


#### Cargue de librerías: 


#### Cargue de bases de datos


#### Describa la estructura de los datos



## Reflexión (Sección 5)

Aquí se espera que incluya preguntas/actividades que permita reflexionar al grupo sobre los alcances y limitaciones de lo aprendido en la resolución del problema expuesto en el taller. Así como reflexiones que conlleven a un mejor aprendizaje y aplicación al campo de la salud pública.


###Ejemplo de los conceptos

- Discusión grupal sobre las barreras para determinar la fecha de contagio y la fuente de infección.
- Debate sobre cómo el estigma social puede afectar la divulgación de información y las estrategias de control.
- Reflexión sobre lo aprendido y discusión sobre cómo mejorar las estrategias de control en futuros brotes y como crear programas de control bajo diferentes circunstancias.

***

### Sobre este documento

Este documento ha sido diseñado por NOMBRE_DE_AUTORES para el Curso Internacional: Análisis de Brotes y Modelamiento en Salud Pública, Bogotá 2023. TRACE-LAC/Javeriana.

#### Contribuciones

- NOMBRE_DE_AUTORES_Y_COLABORADORES


